language: cpp
sudo: required
dist: trusty

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - llvm-toolchain-precise-3.7
            - llvm-toolchain-precise-3.8
            - llvm-toolchain-precise-3.9
        packages:
            - g++-4.9
            - g++-5
            - g++-6
            - clang-3.6
            - clang-3.7
            - clang-3.8
            - clang-3.9

matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-4.9
    
    - compiler: gcc
      env: COMPILER=g++-5
    
    - compiler: gcc
      env: COMPILER=g++-6
    
    - compiler: clang
      env: COMPILER=clang++-3.6
    
    - compiler: clang
      env: COMPILER=clang++-3.7
    
    - compiler: clang
      env: COMPILER=clang++-3.8

    - compiler: clang
      env: COMPILER=clang++-3.9

branches:
    only:
        - master

before_install:
    - if [ "$TRAVIS_OS_NAME" = "linux"  ]; then sudo apt-get -qq update;    fi

before_script:
    - if [ "$COMPILER" = "g++-4.9"      ]; then export CXX="g++-4.9" CC="gcc-4.9";          fi
    - if [ "$COMPILER" = "g++-5"        ]; then export CXX="g++-5" CC="gcc-5";              fi
    - if [ "$COMPILER" = "g++-6"        ]; then export CXX="g++-6" CC="gcc-6";              fi
    - if [ "$COMPILER" = "clang++-3.6"  ]; then export CXX="clang++-3.6" CC="clang-3.6";    fi
    - if [ "$COMPILER" = "clang++-3.7"  ]; then export CXX="clang++-3.7" CC="clang-3.7";    fi
    - if [ "$COMPILER" = "clang++-3.8"  ]; then export CXX="clang++-3.8" CC="clang-3.8";    fi
    - if [ "$COMPILER" = "clang++-3.9"  ]; then export CXX="clang++-3.9" CC="clang-3.9";    fi

script:
    - mkdir build && cd build && cmake .. && cmake --build .

after_success:
    - ./hello_world
    - ./square_root