language: cpp
sudo: required
dist: trusty

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - llvm-toolchain-precise-3.7
        packages:
            - g++-4.9
            - g++-5
            - g++-6
            - g++-7
            - clang-3.6
            - clang-3.7

matrix:
  include:
    - compiler: gcc
        env: COMPILER=g++-4.9
    
    - compiler: gcc
        env: COMPILER=g++-5
    
    - compiler: gcc
        env: COMPILER=g++-6
    
    - compiler: gcc
        env: COMPILER=g++-7
    
    - compiler: clang
        env: COMPILER=clang++-3.6
    
    - compiler: clang
        env: COMPILER=clang++-3.7

branches:
    only:
        - master

before_install:
    - sudo apt-get -qq update

before_script:
    - if [ "$COMPILER" = "g++-4.9" ]; then export CXX="g++-4.9" CC="gcc-4.9"; fi
    - if [ "$COMPILER" = "g++-5" ]; then export CXX="g++-5" CC="gcc-5"; fi
    - if [ "$COMPILER" = "g++-6" ]; then export CXX="g++-6" CC="gcc-6"; fi
    - if [ "$COMPILER" = "g++-7" ]; then export CXX="g++-7" CC="gcc-7"; fi
    - if [ "$COMPILER" = "clang++-3.6" ]; then export CXX="clang++-3.6" CC="clang-3.6"; fi
    - if [ "$COMPILER" = "clang++-3.7" ]; then export CXX="clang++-3.7" CC="clang-3.7"; fi
script:
    - mkdir build && cd build && cmake .. && cmake --build .
    - ./hello_world
    - ./square_root