language: cpp
sudo: required
dist: trusty

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
            - llvm-toolchain-precise-3.7
            - llvm-toolchain-precise-3.8
            - llvm-toolchain-precise-3.9
        packages:
            - g++-4.9
            - g++-5
            - g++-6
            - clang-3.6
            - clang-3.7
            - clang-3.8
            - clang-3.9

matrix:
  include:
    - compiler: gcc
      env: COMPILER=g++-4.9
    
    - compiler: gcc
      env: COMPILER=g++-5
    
    - compiler: gcc
      env: COMPILER=g++-6
    
    - compiler: clang
      env: COMPILER=clang++-3.6
    
    - compiler: clang
      env: COMPILER=clang++-3.7
    
    - compiler: clang
      env: COMPILER=clang++-3.8

    - compiler: clang
      env: COMPILER=clang++-3.9

branches:
    only:
        - /.*/

before_script:
    - export CXX=${COMPILER}
    - mkdir build && cd build
    - cmake -DBUILD_TESTS=1 ..

script:
    - make -j 2

after_success:
    - ./hello_world
    - ./square_root
    - ./salesman
    - ./ps_functions
    - ./tests -s -d yes
