init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

version: '{branch}-{build}'

os:
  - Visual Studio 2015

branches:
  only:
    - /.*/

platform:
  - Win32
  - x64
  
configuration:
  - Debug
  - Release

before_build:
  - cmd: cmake --version
  - cmd: mkdir build
  - cmd: cd build
  - cmd: if "%CONFIGURATION%" == "Release" (cmake -DBUILD_TESTS=1 -A %platform% ..)
  - cmd: if "%CONFIGURATION%" == "Debug" (cmake -DBUILD_TESTS=1 -A %platform% -DDEBUG=ON ..)

build:
  project: build\Moe.sln
  parallel: true
  verbosity: normal


after_build:
  - cmd: cd %CONFIGURATION%
  - cmd: hello_world.exe
  - cmd: square_root.exe
  - cmd: salesman.exe
  - cmd: ps_functions.exe
  - cmd: tests.exe -s -d yes
