init:
- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))

environment:
  home: C:\projects
  cmake: C:\projects\cmake-3.8.0-rc1-win32-x86\bin\cmake.exe
  matrix:
  - generator : Visual Studio 14
    configuration: Debug
    environment:
      cmakeOption: -DDEBUG=ON
      outBuild: C:\projects\moe\build\Debug

  - generator : Visual Studio 14
    configuration: Release
    environment:
      cmakeOption: -DDEBUG=OFF
      outBuild: C:\projects\moe\build\Release

  - generator : Visual Studio 14 Win64
    configuration: Debug
    environment:
      cmakeOption: -DDEBUG=ON
      outBuild: C:\projects\moe\build\Debug

  - generator : Visual Studio 14 Win64
    configuration: Release
    environment:
      cmakeOption: -DDEBUG=OFF
      outBuild: C:\projects\moe\build\Release


version: '{branch}-{build}'

os: Visual Studio 2015

branches:
  only:
    - master

install:
  - cmd: cd %home%
  - ps: wget https://cmake.org/files/v3.8/cmake-3.8.0-rc1-win32-x86.zip -OutFile cmake.zip
  - cmd: 7z x cmake.zip -o"C:\projects" -y > nul
  - cmd: '%cmake% --version'

before_build:
  - cmd: cd %home%\moe
  - cmd: mkdir build
  - cmd: cd build
  - cmd: '%cmake% -G "%generator%" %cmakeOption% ..'

after_build:
  - cmd: 'cd %outBuild%'
  - cmd: hello_world.exe
  - cmd: square_root.exe
  - cmd: salesman.exe

build_script:
  - msbuild C:\projects\moe\build\Moe.sln
